export interface VocabularyEntry { vocabulary_id: string; term: string; normalized_term: string; definition: string | null; part_of_speech: string | null; pronunciation: string | null; examples: string[]; notes: string | null; tags: string[]; source_paper_id: string | null; source_paper_title?: string | null; source_session_id: string | null; source_page_number: number | null; source_selection: Record<string, unknown> | null; created_at: string; updated_at: string; }
export interface VocabularyWritePayload { term: string; definition: string | null; part_of_speech: string | null; pronunciation: string | null; examples: string[]; notes: string | null; tags: string[]; }
async function checked(response: Response): Promise<Response> { if (response.ok) return response; const body = await response.json().catch(() => ({})) as { detail?: { message?: string } }; throw new Error(body.detail?.message ?? `HTTP ${response.status}`); }
export async function listVocabulary(search = ""): Promise<VocabularyEntry[]> { const query = search ? `?search=${encodeURIComponent(search)}` : ""; return (await checked(await fetch(`/api/vocabulary${query}`)).then((response) => response.json()) as { entries: VocabularyEntry[] }).entries; }
export async function createVocabulary(payload: VocabularyWritePayload & { idempotency_key: string }): Promise<VocabularyEntry> { const result = await checked(await fetch("/api/vocabulary", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) })).then((response) => response.json()) as { entry: VocabularyEntry }; return result.entry; }
export async function updateVocabulary(id: string, payload: VocabularyWritePayload): Promise<VocabularyEntry> { const result = await checked(await fetch(`/api/vocabulary/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) })).then((response) => response.json()) as { entry: VocabularyEntry }; return result.entry; }
export async function deleteVocabulary(id: string): Promise<void> { await checked(await fetch(`/api/vocabulary/${id}`, { method: "DELETE" })); }
export type ReviewRating = "unknown" | "fuzzy" | "known";
export async function recordVocabularyReview(payload: { vocabulary_id: string; review_session_id: string; rating: ReviewRating; mode?: "local" | "agent" }): Promise<void> { await checked(await fetch("/api/vocabulary/reviews", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode: "local", ...payload }) })); }
export function vocabularyExportUrl(format: "json" | "csv"): string { return `/api/vocabulary/export?format=${format}`; }
